# Site settings
title: Mia Stevens
email: mstevens.2898@gmail@gmail.com
description: > #  Website for Mia Stevens
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://mstevens20.github.io"
twitter_username: bumbling_along
github_username: mstevens20

### content configuration ###
#favicon:     "/img/favicon.ico"
#touch_icon:  "/img/apple-icon-144x144.png"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
